import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

type SubjectScore = {
  subject_name: string;
  classwork: number | null;
  groupwork: number | null;
  projectwork: number | null;
  test: number | null;
  exam_score: number | null;
  grand_total: number | null;
  grade: string | null;
};

type ReportCardData = {
  studentName: string;
  className: string;
  overallAverage: number | null;
  classPosition: number | null;
  subjects: SubjectScore[];
};

function buildReportCardHtml(data: ReportCardData) {
  const rows = data.subjects
    .map(
      (s) => `
      <tr>
        <td>${s.subject_name}</td>
        <td>${s.classwork ?? "-"}</td>
        <td>${s.groupwork ?? "-"}</td>
        <td>${s.projectwork ?? "-"}</td>
        <td>${s.test ?? "-"}</td>
        <td>${s.exam_score ?? "-"}</td>
        <td><strong>${s.grand_total ?? "-"}</strong></td>
        <td>${s.grade ?? "-"}</td>
      </tr>`,
    )
    .join("");

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1a1830; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          .sub { color: #7a789a; font-size: 13px; margin-bottom: 24px; }
          .stats { display: flex; gap: 24px; margin-bottom: 24px; }
          .stat-label { font-size: 11px; color: #7a789a; }
          .stat-value { font-size: 16px; font-weight: 700; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          th, td { border: 1px solid #e5e3f5; padding: 8px 10px; font-size: 12px; text-align: center; }
          th { background: #eeecff; }
          td:first-child, th:first-child { text-align: left; }
          .footer { margin-top: 40px; font-size: 11px; color: #7a789a; }
        </style>
      </head>
      <body>
        <h1>Student Report Card</h1>
        <div class="sub">${data.studentName} · ${data.className}</div>

        <div class="stats">
          <div>
            <div class="stat-label">Overall Average</div>
            <div class="stat-value">${data.overallAverage != null ? `${data.overallAverage}%` : "—"}</div>
          </div>
          <div>
            <div class="stat-label">Class Position</div>
            <div class="stat-value">${data.classPosition != null ? `#${data.classPosition}` : "—"}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Subject</th><th>CW</th><th>GW</th><th>PW</th><th>Test</th><th>Exam</th><th>Total</th><th>Grade</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>

        <div class="footer">Generated by School Manager</div>
      </body>
    </html>
  `;
}

export async function exportStudentReportCard(data: ReportCardData) {
  try {
    const html = buildReportCardHtml(data);
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      UTI: "com.adobe.pdf",
      mimeType: "application/pdf",
    });
  } catch (error) {
    console.error("REPORT CARD EXPORT ERROR:", error);
    throw error;
  }
}
